spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://shaoxiongrm-bp10dkvhokk30a8ae6odu.mysql.rds.aliyuncs.com:3306/blog
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog.log



