spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 此处填写数据库链接
    username: 此处填写您的数据库账号
    password: 此处填写您的数据库密码
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog.log



