# 线上环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp10dkvhokk30a8ae6o.mysql.rds.aliyuncs.com:3306/blog
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: error
    com.lrm: error
  file: log/blog.log



