# 开发环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: 1002
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: error
    com.lrm: error
  file: log/blog.log



